### ISSUE TITLE
record: Force key to be string on init

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1002]
Affects: dffml==0.4.0

We need to modify the `Record.__init__()` method to have `key = str(key)`

**Comment by kahanikaar** [comment]
I would like to contribute to this issue, will be grateful for guidance to approach this. @pdxjohnny

**Comment by pdxjohnny** [comment]
Read the source code for the `Record.__init__` method. Use `git grep` to find it `git grep -n __init__ -- path/to/record.py_file`

Use the documentation website to find what file the `Record` class is in: https://intel.github.io/dffml/master/search.html?q=Record+class&check_keywords=yes&area=default#

- Click the above link to see how you would search for it
- Figure out what file it is in

**Comment by kahanikaar** [comment]
Made an initial PR. Do review @pdxjohnny
