### ISSUE TITLE
docs: rubric page link not working

### ISSUE THREAD

**Issue by sk-ip** [intel/dffml#1014]
Change the link of the `rubric` page here 
- https://github.com/intel/dffml/blob/master/docs/contributing/gsoc/2021.md#deadlines 
with 
- https://intel.github.io/dffml/master/contributing/gsoc/rubric.html link

**Comment by rajpratyush** [comment]
@pdxjohnny @sk-ip I would like to take up this issue as well?

**Comment by rajpratyush** [comment]
@sk-ip @pdxjohnny can you tell me the location of the file?

**Comment by sk-ip** [comment]
@rajpratyush the location of the file is `dffml\docs\contributing\gsoc\2021.md`
