### ISSUE TITLE
service: dev: docs: build: Convert scripts/docs.sh into dffml/service/dev.py CMD

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1017]
We just need to go through and convert the bash calls to Python or use subprocess where that doesn't make sense

**Comment by rajpratyush** [comment]
can I take up this issue ? @pdxjohnny

**Comment by pdxjohnny** [comment]
@rajpratyush Please read the contribution guidlines https://intel.github.io/dffml/master/contributing/dev_community.html#who-s-working-on-what

**Comment by rajpratyush** [comment]
@pdxjohnny pushed the PR for the last issue working on few more and completed 2 more issues just will push the PR tomorrow.

**Comment by programmer290399** [comment]
I am picking this up. 🙂
