### ISSUE TITLE
scripts: docs: copybutton.js hash out of date

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1030]
`docs` build is failing due to `copybutton.js` having been updated, we need to update the hash in `scripts/docs.sh`.

This issue will be re-opened whenever `copybutton.js` is updated.

**Comment by rajpratyush** [comment]
@pdxjohnny Can you explain me a little bite more?

**Comment by pdxjohnny** [comment]
Sorry @rajpratyush, i forgot to close this
