### ISSUE TITLE
model: autosklearn: CI failing due to timeout error

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1033]
See logs from 2021-03-06: [logs_2541.zip](https://github.com/intel/dffml/files/6143228/logs_2541.zip)

**Comment by nitesh585** [comment]
@pdxjohnny what is the actual error? I mean can you share the snippet of the error.

**Comment by pdxjohnny** [comment]
@nitesh585 I've attached the logs, it looks like the error went away 🤔 thanks for volunteering to look into it anyways though!
