### ISSUE TITLE
ci: lint: commits: Add ci job to validate commit message format

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1040]
We need to add a new CI job under `lint:` within the `.github/workflows/testing.yml` to validate commit message formatting.

Add a new `CMD` class in `dffml/service/dev.py` (along with tests in `tests/service/test_dev.py`) to check that commit message titles match the format specified in https://intel.github.io/dffml/master/contributing/git.html#issue-and-pull-request-title-formatting

**Comment by Pratikrocks** [comment]
@pdxjohnny can I give a try?

**Comment by pdxjohnny** [comment]
@Pratikrocks Yes! Please see https://intel.github.io/dffml/master/contributing/dev_community.html#who-s-working-on-what. As a rule we don't ask if we can do something, we state our intention to try to do it, then follow those guidelines.

**Comment by Pratikrocks** [comment]
Okay @pdxjohnny 👍

**Comment by programmer290399** [comment]
I am picking this issue , would share the validation rules shortly.

**Comment by programmer290399** [comment]
One question @pdxjohnny  : Would we be validating all the past commits as well or only the ones which would be made after this linting feature is merged and are not already in master ?
