### ISSUE TITLE
model: scikit: scikit_base unable to import `dffml.util.crypto`

### ISSUE THREAD

**Issue by mHash1m** [intel/dffml#1077]
```
  File "scripts/docs.py", line 171, in gen_docs
    cls = i.load()
  File "/home/hash1m/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/hash1m/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/hash1m/dffml/model/scikit/dffml_model_scikit/__init__.py", line 326, in <module>
    from .scikit_models import *
  File "/home/hash1m/dffml/model/scikit/dffml_model_scikit/scikit_models.py", line 59, in <module>
    from dffml_model_scikit.scikit_base import (
  File "/home/hash1m/dffml/model/scikit/dffml_model_scikit/scikit_base.py", line 11, in <module>
    from dffml.util.crypto import secure_hash
ModuleNotFoundError: No module named 'dffml.util.crypto'
```

**Comment by programmer290399** [comment]
Hey @mHash1m  ! 
can you share the steps to reproduce this error ?

**Comment by mHash1m** [comment]
Hey @programmer290399,
Try running the docs script `scripts/docs.sh` or using the `sklearnlr` model for that matter. Should occur with anything that's running the `scikit_base` afaik.

**Comment by programmer290399** [comment]
Is this bug only in the Python API ? 

Would [this](https://intel.github.io/dffml/master/quickstart/model.html?highlight=scikitlr#python) be a good example to reproduce this error ?

But this runs fine on the current master .

**Comment by programmer290399** [comment]
> ```
>   File "scripts/docs.py", line 171, in gen_docs
>     cls = i.load()
>   File "/home/hash1m/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
>     return self.resolve()
>   File "/home/hash1m/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/home/hash1m/dffml/model/scikit/dffml_model_scikit/__init__.py", line 326, in <module>
>     from .scikit_models import *
>   File "/home/hash1m/dffml/model/scikit/dffml_model_scikit/scikit_models.py", line 59, in <module>
>     from dffml_model_scikit.scikit_base import (
>   File "/home/hash1m/dffml/model/scikit/dffml_model_scikit/scikit_base.py", line 11, in <module>
>     from dffml.util.crypto import secure_hash
> ModuleNotFoundError: No module named 'dffml.util.crypto'
> ```

Looks like you're using a `conda env` , in that case are you using `conda develop` or `pip install -e` for working in the development mode ?

After  issue #1017  was closed , we no longer have a `docs.sh` script and the `dffml service dev docs` command seems to be working fine on my side.

**Comment by mHash1m** [comment]
@programmer290399 sorry for the late reply. You're right, it didn't pop up after pulling the master. I suppose it got fixed.
