### ISSUE TITLE
docs: Typos in GSoC 2021 Contribution Guide

### ISSUE THREAD

**Issue by kaustubhgupta** [intel/dffml#1084]
While exploring the [dffml GSoC guide](https://intel.github.io/dffml/master/contributing/gsoc/2021/), I encountered some minor typos in the content. I can fix all of them. 

Can any mentor/collaborator assign me this issue so that I can make the PR for the same?

**Comment by programmer290399** [comment]
Hey @kaustubhgupta  ! 

I am not a mentor but I guess I can answer your question. 

Please see [Guidelines here](https://intel.github.io/dffml/master/contributing/dev_community.html#who-s-working-on-what) .

As a rule we don't ask if we can do something, we state our intention to try to do it, then follow those guidelines.

**Comment by kaustubhgupta** [comment]
Oh, okay. I am working on this issue.
