### ISSUE TITLE
high_level:  Move code into a directory and splitting out into files. 

### ISSUE THREAD

**Issue by programmer290399** [intel/dffml#1170]
## Pain Point

It is currently not possible to import some high-level functionalities in other core parts of dffml like `model.py`  due to formation of circular import chains. 

Which blocks implementation of archive support for  #662 

### References
* https://github.com/intel/dffml/pull/1155#discussion_r667428972
* [Weekly Sync 2021-07-13@45:46](https://youtu.be/B10Cqh1CTN0?t=2746)
 

## Proposed Solution

Split the high_level code into a directory and splitting out into files such as high_level/dataflow.py (similar to cli)

A proposed split tree is given below :

```
high_level
├── __init__.py
├── high_level.py
│   └── _records_to_sources
├── dataflow.py
│   └── run
├── source.py
│   ├── save
│   └── load
└── ml.py
    ├── train
    ├── accuracy
    └── predict
```

Tree structure made with [tree.nathanfriend.io](https://tree.nathanfriend.io/)

**Comment by programmer290399** [comment]
ping @pdxjohnny

**Comment by pdxjohnny** [comment]
Let's get that helper function out of there. Otherwise looks great!

```
(echo -e '"""\nHelper functions for dealing with internal data types\n"""\n\n'&& grep -A 39 def\ _records -- dffml/high_level.py | sed -e 's/def _r/def r/') | tee dffml/util/internal.py
```
