### ISSUE TITLE
accuracy: `AccuracyScorer.load()` doesn't recognize scikit scorer entrypoints.

### ISSUE THREAD

**Issue by mHash1m** [intel/dffml#1180]
I'd imagine we would want this behaviour of dynamic loading for scikit scorers as well otherwise things might get confusing

![Screenshot from 2021-07-31 01-07-00](https://user-images.githubusercontent.com/58783659/127707032-284c9409-5e01-4276-8a71-700282e53f81.png)

**Comment by pdxjohnny** [comment]
Did you re-run the install on `model/scikit`?

```console
$ pip install -e model/scikit[dev]
```

**Comment by mHash1m** [comment]
@pdxjohnny this one always gets me. Thank you!

**Comment by pdxjohnny** [comment]
Right! Me too, we could consider doing something like `cve-bin-tool` does and re-running `python setup.py egg_info` on `Entrypoint.load` if we're in development mode

**Comment by mHash1m** [comment]
Yeah, that makes sense!
