### ISSUE TITLE
accuracy: Rename high level accuracy() to score()

### ISSUE THREAD

**Issue by mHash1m** [intel/dffml#1181]
## Pain Point

As of the recent merges, the high-level `accuracy()` function returns scores w.r.t different scorers selected. These could also be a resultant value of error.
Accuracy generally follows the phenomenon of "greater is better" but that is no longer the case here.
This could possibly be confusing for new users.

## Proposed Solution

Change `accuracy()` to something like `score()` or `evaluate()`

**Comment by pdxjohnny** [comment]
Let's discuss this in the meeting, I think this might make sense.

**Comment by programmer290399** [comment]
I think I can pick this up if no one else is working on it , @mHash1m  are you working on this ?

**Comment by mHash1m** [comment]
@programmer290399 sure! I didn't get to this one yet.
