### ISSUE TITLE
optimizer: change plugin name

### ISSUE THREAD

**Issue by mHash1m** [intel/dffml#1200]
## Pain Point

While it is a good name, it can be easily confused with optimisation algorithms used by different machine learning libraries to train a model. These optimisation algorithms are low-level implementations responsible of reducing loss in a model and are nothing close to hyper parameter tuning. 

## Proposed Solution

A different name that would be suggestive of tuning characteristics. Perhaps, `tuners` would make a lot more sense.

**Comment by pdxjohnny** [comment]
In agreement with `tuner`

**Comment by programmer290399** [comment]
are we good to go with tuner then ?,  shall I make a PR for this ? @pdxjohnny
