### ISSUE TITLE
CONTIRIBUTING: Add note about using black via VSCode

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#121]
https://code.visualstudio.com/docs/python/editing#_formatting

**Comment by sk-ip** [comment]
Hello @pdxjohnny I would like to work on this issue, please point me to the files where changes are to be made.

**Comment by pdxjohnny** [comment]
@sk-ip https://github.com/intel/dffml/blob/master/docs/contributing/style.rst#file-formatting
