### ISSUE TITLE
community: Logo

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1215]
We need a logo!

# Vote: https://strawpoll.com/whu887f89

Let's shoot for SVG format. Ideally with design files as well.

**Comment by mHash1m** [comment]
Didn't have an option to save in svg format but I guess that can be done later. And I hope there's nothing wrong with choosing existing icons
![DFFML-5](https://user-images.githubusercontent.com/58783659/135106470-a2091c83-7bab-4a6f-8ee0-5baab4a25eaa.png)
![DFFML-3](https://user-images.githubusercontent.com/58783659/135106501-6f0ba5f0-0314-4432-8d40-f77cdd9c05cd.png)
![DFFML-4](https://user-images.githubusercontent.com/58783659/135107914-e4fca065-202f-4d6b-8789-024f4554842d.png)
![DFFML-logos_white](https://user-images.githubusercontent.com/58783659/135106610-10f46632-a475-422c-8785-5817e6c3a875.png)
![DFFML-6](https://user-images.githubusercontent.com/58783659/135107650-f127683e-9d86-4f23-b8d3-ddc3be06092b.png)
![DFFML-logos_white](https://user-images.githubusercontent.com/58783659/135106722-b73dc291-cf2e-4736-8e9e-ed753f2009f5.png)
![DFFML-logos_transparent](https://user-images.githubusercontent.com/58783659/135107237-aba98af9-0b39-4d46-8acc-dd4f465abc9c.png)
![DFFML-logos_transparent](https://user-images.githubusercontent.com/58783659/135107212-316f1767-091d-4a8f-90dc-648701dfb8f6.png)

**Comment by programmer290399** [comment]
#### 1. The octagon design looks really good, one thing that maybe we can add is some arrows on the lines inside it, to symbolize the data flow part of our project.
#### 2. We should look forward to adapting logos that look, good independent of the theme, I mean some logos look good on light-themed pages but look bad on dark ones and vice versa. We should choose one that looks good on both types of themes.

**Comment by Devesh-Shirsath** [comment]
This look great!
Since ill be working on User Interface Design, maybe ill try playing with this logos colour combination. Maybe that might help us establish a design guide which i might use while designing the webui

**Comment by Devesh-Shirsath** [comment]
ill try making it more attractive, and will share svg format and source file

**Comment by mHash1m** [comment]
@programmer290399 yes, I chose the icon thinking of nodes as different API's and the octagon as DFFML linking and wrapping everything together. 

@Devesh-Shirsath I'm not much of a designer so feel free to go about it as you like. If you could also add the arrows in the logo as Sahil mentioned, that'd be great!

**Comment by Devesh-Shirsath** [comment]
sure

**Comment by Devesh-Shirsath** [comment]
![image](https://user-images.githubusercontent.com/43561270/135159822-138e732e-549f-4c7c-a931-e5f747ec3bd2.png)

**Comment by Devesh-Shirsath** [comment]
![image](https://user-images.githubusercontent.com/43561270/135160457-65b60ab9-8633-48aa-a8a3-446d92972d40.png)
1. made a user flow icon with L as an arrow

![image](https://user-images.githubusercontent.com/43561270/135160575-42b70a8a-c25a-4541-9071-cd27e31c7113.png)
2. plain option

![image](https://user-images.githubusercontent.com/43561270/135160737-c8f35718-be71-4092-9086-d7047b0cadf4.png)
3. colorful option

**Comment by Devesh-Shirsath** [comment]
personally i like the last one

**Comment by Devesh-Shirsath** [comment]
logos like these will go well with the website/webapp
if we add a tagline to the logo, it'll get harder to manage spacing etc in the future hence I avoided it. we can add a tagline on the landing page somewhere

**Comment by Devesh-Shirsath** [comment]
pls share your feedbacks :)

**Comment by programmer290399** [comment]
In my opinion 3 looks great, can we have the font arrangement like 2 in 3 ? I mean those two f's look a bit smaller actually leaves a subtle impression in the mind as compared to the plain font in 3. 

What do you think @Devesh-Shirsath  @mHash1m ?

**Comment by Devesh-Shirsath** [comment]
![image](https://user-images.githubusercontent.com/43561270/135221489-73f33caf-7a98-4e29-b52b-ee5abb537d8d.png)
hows this?

**Comment by Devesh-Shirsath** [comment]
These are logos in SVG format
1. DFFML icon
2. logo for dark BG
3. logo for light BG
https://drive.google.com/file/d/1FgYAPIBbH4XkMqDQLmMDEvIEumsHt5Ck/view?usp=sharing

**Comment by programmer290399** [comment]
@pdxjohnny , can we approach [Jason Long](https://github.com/jasonlong), because as far as I know he has made logos for other Open Source projects as well.

**Comment by programmer290399** [comment]
Tagging @jasonlong

**Comment by jasonlong** [comment]
I had an idea pop into my head today so I played around with it a bit. The concept uses a [Guilloche Pattern](https://www.wikiwand.com/en/Guilloch%C3%A9) with all of the loops and colors representing the wide range of ML libraries your project facilitates working together.

Let me know a general :+1: / :-1: on how this feels.

![dffml-logo-concept-v1](https://user-images.githubusercontent.com/6104/147286040-98736d7b-90b9-4c44-8e43-9fa4071b101c.png)

**Comment by programmer290399** [comment]
ping: @pdxjohnny, please 👀 
We should probably discuss this in the next meet.

**Comment by pdxjohnny** [comment]
Neat! This is great! :D Thank you @jasonlong

**Comment by jasonlong** [comment]
Let me know if you have any tweaks in mind. Otherwise, I can get you some SVGs for you to use.

**Comment by Devesh-Shirsath** [comment]
This looks awesome and fresh!!
would it look nicer if we had fewer loops?
because I think a logo is nicer if people can draw it by hand easily!

**Comment by jasonlong** [comment]
@Devesh-Shirsath Thank you for the feedback. I don't think a Guilloche pattern is something people will ever be able to draw accurately, but I did explore some variations with fewer loops to simplify the shape. Going with fewer loops than this (20) starts to feel like the React and Atom editor logos.

Here's an updated version with colored and 1 color variations.

<img width="786" alt="dffml-logo-concept-v2" src="https://user-images.githubusercontent.com/6104/148128951-7a63c8b4-6c3a-4429-992f-eeec39a1f08f.png">

**Comment by programmer290399** [comment]
> @Devesh-Shirsath Thank you for the feedback. I don't think a Guilloche pattern is something people will ever be able to draw accurately, but I did explore some variations with fewer loops to simplify the shape. Going with fewer loops than this (20) starts to feel like the React and Atom editor logos.
> 
> Here's an updated version with colored and 1 color variations.
> 
> <img alt="dffml-logo-concept-v2" width="786" src="https://user-images.githubusercontent.com/6104/148128951-7a63c8b4-6c3a-4429-992f-eeec39a1f08f.png">

I love the top row in this one, I think we should finalize this one. Let's do a final vote on this. Ping: @pdxjohnny @sakshamarora1 @yashlamba @0dust @Devesh-Shirsath

**Comment by jasonlong** [comment]
To clarify, they're all the same logo but I included single color options for when that's a constraint. The final set of SVGs would contain both color versions and single color.

**Comment by 0dust** [comment]
> > @Devesh-Shirsath Thank you for the feedback. I don't think a Guilloche pattern is something people will ever be able to draw accurately, but I did explore some variations with fewer loops to simplify the shape. Going with fewer loops than this (20) starts to feel like the React and Atom editor logos.
> > Here's an updated version with colored and 1 color variations.
> > <img alt="dffml-logo-concept-v2" width="786" src="https://user-images.githubusercontent.com/6104/148128951-7a63c8b4-6c3a-4429-992f-eeec39a1f08f.png">
> 
> I love the top row in this one, I think we should finalize this one. Let's do a final vote on this. Ping: @pdxjohnny @sakshamarora1 @yashlamba @0dust @Devesh-Shirsath

Love the first one!

**Comment by programmer290399** [comment]
Final Pole up here: https://strawpoll.com/whu887f89
Please vote before month-end...

Ping: @jasonlong @Devesh-Shirsath @0dust

**Comment by pdxjohnny** [comment]
![image](https://user-images.githubusercontent.com/5950433/151998405-9659b648-0792-46a1-ade7-e041746d7db6.png)

![image](https://user-images.githubusercontent.com/5950433/151998623-7ede4b07-3f4b-40ef-ad37-a047ceb9fcd2.png)

**Comment by jasonlong** [comment]
Sorry for the delay. I'll get this added soon. 👍🏼

**Comment by pdxjohnny** [comment]
Thank you @jasonlong!! So cool that the project has a logo. We'll be able to put the logo on the GSoC project page this year. https://python-gsoc.org/ideas.html

**Comment by jasonlong** [comment]
Happy to help!
