### ISSUE TITLE
README : Conditionally render dark/light mode logos depending on user's GitHub theme

### ISSUE THREAD

**Issue by programmer290399** [intel/dffml#1305]
## Proposed Solution

It is a simple fix : https://stackoverflow.com/a/70200610/10108465

**Comment by programmer290399** [comment]
@pdxjohnny please add label of good-first-issue here 🙂

**Comment by Onkar627** [comment]
@programmer290399 are you referring to DFFML logo in the readme file?

**Comment by programmer290399** [comment]
Yes @Onkar627
