### ISSUE TITLE
How do I set up for "Contribution" ?

### ISSUE THREAD

**Issue by AnkitKashyap0709** [intel/dffml#1364]
On the GitHub page of dffml, the "[Contribution](https://intel.github.io/dffml/main/contributing/index.html)" documentation link is meant to guide the contributors on how to set up the dev. environment and start fixing the bugs. But that link didn't work. Need some help in clarifying those things from my fellow developers or our mentor.

**Comment by programmer290399** [comment]
I guess you're looking for this page: https://intel.github.io/dffml/master/contributing/index.html

If that is it then please close the issue, or feel free to ask for more help on gitter chat.
