### ISSUE TITLE
zsh implementation

### ISSUE THREAD

**Issue by TirelessClock** [intel/dffml#1375]
Hey @pdxjohnny @programmer290399 @mHash1m ,
While setting up, I was using zsh, and one pain point I experienced was writing `[dev]` while installing the package in development mode. Only later did I find out that zsh has a different meaning for square brackets and we have to write [ ] within quotes. 
I wanted to ask if this point should be added to the [Contributing](https://intel.github.io/dffml/master/contributing/dev_env.html) page, for anyone using zsh?

**Comment by pdxjohnny** [comment]
Please do!

**Comment by TirelessClock** [comment]
@pdxjohnny Done! #1378
