### ISSUE TITLE
skel: Capitalize version

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#139]
```python
setup(
    version=version
)
```

should be

```python
setup(
    version=VERSION
)
```

**Comment by NeerajBhadani** [comment]
"version" is a variable. If we capitalize this then we also need to capitalize where we are defining the version as well.

Please clarify which version needs to be capitalize.

**Comment by pdxjohnny** [comment]
All instances of the variable `version` need to be replaced with `VERSION`, or else the packages fail to install.

`version = ast.literal_eval(line.strip().split('=')[-1].strip())` -> `VERSION = ast.literal_eval(line.strip().split('=')[-1].strip()) `
