### ISSUE TITLE
docs: contributing: editors: vscode: Explain how to venv

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#1433]
https://intel.github.io/dffml/main/contributing/editors/vscode.html

**Comment by pyther-hub** [comment]
what I understand from this request is that we have to add automative venv initialization in the json file.
Is this correct and shall I proceed with it?

**Comment by pyther-hub** [comment]
@pdxjohnny please provide some insights to the issue here

**Comment by pyther-hub** [comment]
sir I have made changes for the same but I am not able to find where the lint is failing in github actions

**Comment by pyther-hub** [comment]
@pdxjohnny please provide some extra information over this

**Comment by sayefiqb** [comment]
@pdxjohnny Cqn you please assign this to me.
