### ISSUE TITLE
Personal identity 

### ISSUE THREAD

**Issue by Pacje** [intel/dffml#1522]
Wow! Brilliant work! My dilemma, stolen identity it's on dark web. Recoverable? I don't work on Alice. Can she restore my life?

_Originally posted by @Pacje in https://github.com/intel/dffml/discussions/1406#discussioncomment-8250586_

**Comment by pdxjohnny** [comment]
Hello! I don't know anything about identity recovery. Alice is an abstract architecture for an AI we haven't finished yet, so maybe one day! But unfortunately not today.

I wish you the best of luck though!
