### ISSUE TITLE
Automate the training process (with auto-sklearn)

### ISSUE THREAD

**Issue by kRiShNa-429407** [intel/dffml#1527]
## Pain Point

Automate the training proess.

## Proposed Solution

We can use auto-sklearn in classification ml problems to automate the training process, it gives a leaderboard ranking of different models to easily select one of them for our problem.

**Comment by pdxjohnny** [comment]
Are these docs relevant here? Or are you looking for something more?

- https://intel.github.io/dffml/main/plugins/dffml_model.html?highlight=auto+sklearn#autoregressor
- https://github.com/intel/dffml/tree/c1184c3cb99c5bf9d04a4b7c79f8799303a38d12/model/autosklearn/examples/autoclassifier

**Comment by kRiShNa-429407** [comment]
Okk
