### ISSUE TITLE
docs: CONTRIBUTING and HACKING are almost the same thing, combine them

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#166]

**Comment by Patil2099** [comment]
@pdxjohnny  Can I work on this?

**Comment by pdxjohnny** [comment]
@Patil2099 That would be great! thanks!

**Comment by pdxjohnny** [comment]
I think we want everything to be in CONTRIBUTING.md

**Comment by Patil2099** [comment]
@pdxjhonny what should be the name of the combined file ?

**Comment by pdxjohnny** [comment]
Let's take HACKING.md and CONTRIBUTING.md and merge the contents into `CONTRIBUTING.md`.
