### ISSUE TITLE
examples: shouldi: safety: Use communicate instead of stdin.write

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#172]
We should remove the use of `stdin.write` and replace it with just using the [`asyncio.subprocess.Process.communicate`](https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.asyncio.subprocess.Process.communicate) call

https://github.com/intel/dffml/blob/452a182b0ce773df3ccc7bb40eb8bfe88d3a59e5/examples/shouldi/shouldi/safety.py#L22-L43

**Comment by Patil2099** [comment]
@pdxjohnny  Can I work on it?

**Comment by Yash-Varshney** [comment]
hello community !! I am very new to open source and learning to contribute. I just made my first PR but I am having error in testing . can anyone help out ?

**Comment by pdxjohnny** [comment]
@Yash-Varshney Hi Yash! Thanks! I'm sorry I was missleading with the issue here. What we really need to do is replace the calls to `proc.stdin.write/close` by just using the `communicate` method, which can take a parameter, `input`.

**Comment by Yash-Varshney** [comment]
@pdxjohnny thanks for the clarification..  can you check out the PR i just made .. thanks
