### ISSUE TITLE
base: BaseConfigurable produces odd typenames in conjection with docs.py

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#194]
![image](https://user-images.githubusercontent.com/5950433/64466322-40c0f400-d0c6-11e9-86ea-bcd9e27e432e.png)

Introduced in 5bf570191f54ae97f21764cc867b1f5f652e1355

**Comment by amit6663** [comment]
@pdxjohnny can i work on this issue

**Comment by pdxjohnny** [comment]
Hi @amit6663 thank you, but this issue may get fixed when #164 is completed. So let's hold off on this for now.
