### ISSUE TITLE
service: http: Add OpenAPI definition

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#200]
We need to create an OpenAPI definition file for the HTTP API

Use: https://inspector.swagger.io
And the docs at: https://intel.github.io/dffml/master/plugins/service/http/api.html

**Comment by Patil2099** [comment]
@pdxjohnny Can I work on this?

**Comment by pdxjohnny** [comment]
That'd be great, thanks!

**Comment by pdxjohnny** [comment]
I'm going to consider this open until I see a WIP PR in case you got too busy we'll leave this open for others, sounds like someone was interested in working on it.
