### ISSUE TITLE
source: Replace ENTRY_POINT with base_entry_point

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#223]
We can remove the `ENTRY_POINT` and `ENTRY_POINT_NAME` class variables if we add the `base_entry_point` decorator to `BaseSource`.

https://github.com/intel/dffml/blob/2a23f55acaac69c7a1840260b0ede694216c2007/dffml/source/source.py#L51-L58

```python
@base_entry_point("dffml.source", "source")
 class BaseSource(BaseDataFlowFacilitatorObject): 
     """ 
     Abstract base class for all sources. New sources must be derived from this 
     class and implement the repos method. 
     """
```

**Comment by raghav-ys** [comment]
@pdxjohnny - can i work on this?

**Comment by pdxjohnny** [comment]
@raghav-ys Yes please do!
