### ISSUE TITLE
df: memory: Remove NotificationSet memory if unused

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#229]
https://github.com/intel/dffml/blob/8577ca57a0bad2c63b860cdd585ae6ca3e4e8fe9/dffml/df/memory.py#L172-L173

Remove `self.memory`, not sure if anything will break. If the tests all pass, we should be good.

**Comment by imgovind** [comment]
Hey I removed it, but there seems to be three tests failing 🤔 
`test_run (tests.test_cli.TestOperationsAll) ... ERROR
test_run (tests.test_cli.TestOperationsRepo) ... ERROR
test_run (tests.test_df.TestRunner) ... ERROR`

**Comment by pdxjohnny** [comment]
@imgovind you'll also need to remove this:

https://github.com/intel/dffml/blob/8577ca57a0bad2c63b860cdd585ae6ca3e4e8fe9/dffml/df/memory.py#L134

**Comment by imgovind** [comment]
Hey after making those changes, all the tests passed. 
Created a PR with those changes 
https://github.com/intel/dffml/pull/230
