### ISSUE TITLE
repo: Repo.src_url should be Repo.key

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#233]
DFFML started as a project centred around Git repos. As such, the unique key for a Git repo was the upstream source URL. `src_url` was used as the parameter to hold the unique key.

Now that DFFML has become more general purpose, we need to change *all* references of `src_url` to `key`. Hopefully this is as simple as find and replace...

**Comment by 0dust** [comment]
@pdxjohnny _all_ references of `src_url` means literally **all** references in the entire code, or only references of `src_url` in `repo.src_url` ?

**Comment by pdxjohnny** [comment]
@0dust **all** meaning the entire codebase
