### ISSUE TITLE
shouldi: golang: go vet static analysis

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#244]
References:
- https://blog.trailofbits.com/2019/11/07/attacking-go-vr-ttps/
- https://github.com/mre/awesome-static-analysis#go

This is part of a larger effort to create a meta static analysis tool, [shouldi](https://intel.github.io/dffml/tutorials/operations.html).

To do that, we need to write functions which wrap various static analysers (similarly to how the safety and bandit operations work in the tutorial).

For the test for this operation, you'll need to figure out how to download a go repo from github (https://github.com/nightlyone/lockfile, https://github.com/nightlyone/lockfile/archive/0ad87eef1443f64d3d8c50da647e2b1552851124.tar.gz, might be a good canidate) then extract it to a temporary directory where the operation will be given as the path to scan. Make the operation run the `go vet` command, parse the output, and return a reasonable summary in a `dict`.

The download code was added here: https://github.com/intel/dffml/commit/e80878961372ad1ab8059e86b7eb146f0b217811

See https://github.com/intel/dffml/commit/b33798ca2acfda52c0e4aa20d4224305564b43f0#diff-5541e34e4e2a46f817ef0731c956a64a for example usage

**Comment by Yash-Varshney** [comment]
update : we're using **Golangci-lint** module instead of **Go-vet** and also using a different test case because of no error in the given one.

**Comment by Yash-Varshney** [comment]
hey @pdxjohnny . I believe the motive of this issue has been achieved.
Thanks

**Comment by pdxjohnny** [comment]
@Yash-Varshney Thanks!
