### ISSUE TITLE
util: entrypoint: entry_point should be have no underscore

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#265]
Change all instances of entry_point to entrypoint. Except for in setup.py files.

**Comment by aghinsa** [comment]
@pdxjohnny  does this also include 
* `entry_points` -> `entrypoints`
* `ENTRY_POINT` -> `ENTRYPOINT`

**Comment by pdxjohnny** [comment]
@aghinsa 

> @pdxjohnny does this also include
> 
>     * `entry_points` -> `entrypoints`
> 

No

>     * `ENTRY_POINT` -> `ENTRYPOINT`

Yes

**Comment by aghinsa** [comment]
shall i add it with [#274 ](https://github.com/intel/dffml/pull/274)

**Comment by pdxjohnny** [comment]
> shall i add it with [#274 ](https://github.com/intel/dffml/pull/274)

Let's do that in a separate pull request, thanks!

**Comment by aghinsa** [comment]
Okay
