### ISSUE TITLE
source: csv: Add config to load data from filename

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#279]
https://github.com/intel/dffml/blob/c0899bc063ec6c2d3f32919db5a62305ccd4f2ec/dffml/source/csv.py#L46-L50

Add a config option which is a list of strings, which are the column names which should have their data replaced with the contents of the file for which they had the filename of as their value initially.

https://github.com/intel/dffml/blob/c0899bc063ec6c2d3f32919db5a62305ccd4f2ec/dffml/source/csv.py#L192-L194

If `key` (column name) is in the new config (`files` or something) then do

```python
row[key] = pathlib.Path(value).read_bytes()
```

Make sure there is a testcase for it.

**Comment by pdxjohnny** [comment]
@sakshamarora1 is working on this as a part of #272

**Comment by sakshamarora1** [comment]
@pdxjohnny this issue has been solved by #399 ?

**Comment by pdxjohnny** [comment]
It has been solve by that indeed! Thank you @ sakshamarora1!
