### ISSUE TITLE
feature: Remove evaluation code

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#289]
There is a bunch of code in `dffml/feature/feature.py` that isn't being used. For example the `calc`, `parse`, and `fetch` methods. And all the stuff relating to running those methods from the `Features` class.

**Comment by Yash-Varshney** [comment]
thanks for the issue @pdxjohnny. I will like to work on it, I have a question do we just remove those methods or should we comment them out ( if they are needed in coming future ) ?

**Comment by pdxjohnny** [comment]
Hi @Yash-Varshney, they should be removed. You'll need to go through the test code to and remove the tests associated with them. Thanks!

**Comment by Yash-Varshney** [comment]
@pdxjohnny  please review the commit !!

**Comment by pdxjohnny** [comment]
@Yash-Varshney I'll get to this soon. Sorry I'm pretty busy today. Hopefully today or tomorrow. Can I get you do take these changes and apply them on top of the master branch? I think you'll just need to

```console
$ git fetch --all
$ git merge origin/master
```

and then push.

Thanks!

**Comment by Yash-Varshney** [comment]
@pdxjohnny  I did that and it says that everything is up-to-date.
