### ISSUE TITLE
util: crypto: Create secure_hash and insecure_hash functions

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#297]
Throughout the codebase we have calls to `hashlib`, usually `md5`, `sha256`, or `sha384`.

It would be good to have the calls to hashlib go through a helper function. So we can better track where hashes are being used for convenience (to shorten an otherwise long value), or where hashes are being used there might be a security consequnce to using the wrong hash.

Change to `insecure_hash`
- `md5` is currently only used in the dataflow visualization.
- In the model saving and loading code (`_filename` and similar)

Use `secure_hash`
- Everywhere in df/memory.py (until further notice)
- Everywhere else

**Comment by kahanikaar** [comment]
I would like to work on this issue, will be grateful for guidance to approach this. @pdxjohnny

**Comment by kahanikaar** [comment]
Initial PR made. Do review. @pdxjohnny
