### ISSUE TITLE
feature: Replace Feature with DefFeature

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#303]
We need to move from class based approach for `Feature`s to instance based.

Right now features are still setup for evaluation (#289) this makes no sense with the rest of the codebase at this point. We must clean this up.

Other than that we also need to make `Feature` a dataclass or namedtuple or something. The point here being that `.name()` should just be `.name` and `.NAME` shouldn't exist anymore (same for dtype).

**Comment by Naeemkh** [comment]
@pdxjohnny, I am working on this issue.

**Comment by pdxjohnny** [comment]
@Naeemkh Awesome! This will be great!

**Comment by pdxjohnny** [comment]
Essentially, we want to remove this code:

https://github.com/intel/dffml/blob/4c1e7870dba12c298d5a7f4740a23af634cacb7e/dffml/feature/feature.py#L160-L187

And replace

https://github.com/intel/dffml/blob/4c1e7870dba12c298d5a7f4740a23af634cacb7e/dffml/feature/feature.py#L19

With

```python
@dataclasses.dataclass
class Feature:
    name: str
    dtype: Type # from typing import Type
    length: Union[int, List[int]]

    # ... All the existing methods in feature (but not dtype and length)
```

We'll also go through and remove all references to `DefFeature` and replace them with `Feature`

**Comment by pdxjohnny** [comment]
Right now to create a new `Feature` you have to make a whole new `class`. What we're trying to do here is have `Feature` be a class. And have features be instances of that class. Rather than other classes which are subclasses of `Feature`.
