### ISSUE TITLE
docs: usage: integration: MySQL connection errors on db load

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#314]
Under [Demo App Setup](https://intel.github.io/dffml/usage/integration.html#demo-app-setup), add a note after starting `maintained_db` saying that it will take a bit to start up.

Add a section before loading the data saying to run

```console
$ docker logs maintained_db 2>&1 | grep ready
2020-01-12  6:37:22 0 [Note] mysqld: ready for connections.
2020-01-12  6:37:48 0 [Note] mysqld: ready for connections.
```

You must see `ready for connections` displayed twice before the import will work.

**Comment by aghinsa** [comment]
I'll work on this.
