### ISSUE TITLE
model: tensorlfow: dnnc: Make classification property predict

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#316]
To maintain consistancy with the other models, we should rename the `classification` property to `predict` in `dnnc.py`

Reporter: @aghinsa

**Comment by aghinsa** [comment]
changes in https://github.com/aghinsa/dffml/commit/fd6c91b06aa41620cdd07eff7ce7f267d086eaf4,in pr https://github.com/intel/dffml/pull/274
