### ISSUE TITLE
model: scikit: Config option to choose how accuracy works

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#322]
Reporter: @0dust 

Accuracy could be multiple things, add a property to config to let use decide what they want it to mean.

**Comment by TakshKamlesh** [comment]
Which algorithm is used currently for calculating accuracy??

**Comment by pdxjohnny** [comment]
@TakshKamlesh I can't remember what @0dust was thinking with this, but the following places are where we'd need to change the code (I think)

https://github.com/intel/dffml/blob/6a11e9bf64186c0c32c6c15915c6cff81534e298/model/scikit/dffml_model_scikit/scikit_base.py#L157-L203

https://github.com/intel/dffml/blob/6a11e9bf64186c0c32c6c15915c6cff81534e298/model/scikit/dffml_model_scikit/scikit_base.py#L93-L108

https://github.com/intel/dffml/blob/6a11e9bf64186c0c32c6c15915c6cff81534e298/model/scikit/dffml_model_scikit/scikit_models.py#L203-L245

**Comment by TakshKamlesh** [comment]
Thanks, could I know where the config class for accuracy is?? I am not able to find it.

**Comment by 0dust** [comment]
Sorry guys I am a bit late here!!
@pdxjohnny It was about giving the flexibility to decide on which metric will be used when running `accuracy`. So currently it's hardcoded and we can access the model's performance using the hardcoded metric only. But, if someone is interested in evaluating the model's performance let's say using `f1_score` and then next time using `precision` then there should be an option to choose it.

**Comment by pdxjohnny** [comment]
Closed in favor of #779
