### ISSUE TITLE
cli: dataflow: diagram: Show links on conditions

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#327]
When creating a dataflow diagram inputs and outputs and conditions are shown. But conditions do not show with their 

https://github.com/intel/dffml/blob/01d921ce610d809ef3a941d828c8d8c3b4b853ba/dffml/cli/dataflow.py#L308-L397

In the [Integrating Machine Learning](https://intel.github.io/dffml/master/usage/integration.html) usage example we generate a dataflow with `check_if_valid_git_repository_URL` and `clone_git_repo`. `clone_git_repo` has a condition which comes from `check_if_valid_git_repository_URL`. But currently there is no arrow between them. When this issue is complete there will be an arrow from `check_if_valid_git_repository_URL` to `clone_git_repo`.

![mermaid-sql_update](https://user-images.githubusercontent.com/5950433/72476778-dec67880-37a2-11ea-8925-1ac24b23ee06.jpg)

**Comment by 0dust** [comment]
@pdxjohnny This is what we want in _simple_ mode, right?

![mermaid-diagram-20200528085557](https://user-images.githubusercontent.com/29033531/83095489-10404080-a0c1-11ea-8298-84472e98635e.png)
How should the connections be when not using _simple_ mode?
