### ISSUE TITLE
model: vowpal wabbit

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#328]
https://vowpalwabbit.org/tutorials/cmd_first_steps.html

**Comment by pdxjohnny** [comment]
@0dust if you start on this can you please ping @rahulunair in the PR for review. Thanks!

**Comment by 0dust** [comment]
Sure, I will possibly open the PR tomorrow and let him know.

**Comment by pdxjohnny** [comment]
Sweet!
