### ISSUE TITLE
df: types: Input validation option to use operations within DataFlow

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#382]
If `validation` parameter of definition is set to an operation's instance name within a dataflow use the output of that operation as the validation.

> Note, for now, obviously the operation can only have one input and one output. Or else we wouldn't know which to choose.

**Comment by aghinsa** [comment]
working on this

**Comment by pdxjohnny** [comment]
Some ideas.

The orchestrator waits for new input sets to enter the network, then it dispatches operations. Since we want to run an operation, and we need to operation to be fully setup (instantiated and configured just like the rest of the operations in the dataflow) we'll want to dispatch the operation in the same place we're dispatching the other operations (`run_operations_for_ctx`).

#### `Input`

Since this is all asynchronous, we need to track if an input has been validated yet. We can't just assume it's been validated right away (as we had before since those functions weren't asynchronous) It probably makes sense to modify `Input` to add a `validated` bool parameter, which tracks if the input has been validated yet or not. When an `Input` is instantiated, it's `validated` parameter should be set to `False` if the `validation` parameter is a string (to signify the operation instance name to be used to validate), otherwise it should be `True`.

#### `MemoryInputNetworkContext`

Whenever an input set is created within the DataFlow we `add` it do the `MemoryInputNetworkContext`. We now want to keep un`validated` inputs away from `validated` inputs., Anything that get's `add`ed to the `input_notification_set` comes out in `run_operations_for_ctx`

https://github.com/intel/dffml/blob/ad18dcc35c2b709d811cea6bd897e7868fec664d/dffml/df/memory.py#L1361-L1368

To keep things separate, instead of `ctx.add`ing the `input_set` (Side note: #401), we should remove any un`validated` inputs from the `input_set` (probably would be good to add a method to `BaseInputSet` for this which takes the `Input` to be removed, then based on `uid` searches through its internal list and removes the matching one). The first argument in the call to `ctx.add` should now be a tuple, the first element being an input set containing the unvalidated inputs (so add them to a new set as you remove them), and the second being the valid input set. If there are no invalid inputs, make `None` the first element of the tuple.

https://github.com/intel/dffml/blob/ad18dcc35c2b709d811cea6bd897e7868fec664d/dffml/df/memory.py#L250-L254

Also, we need to make sure that `Input`s which are not `validated` do not get mingled with the rest of the inputs (so they don't end up in any permutations). By adding the `remove` method to the input set then the input won't show up as an `item` in this loop and everything should be okay.

https://github.com/intel/dffml/blob/ad18dcc35c2b709d811cea6bd897e7868fec664d/dffml/df/memory.py#L263-L278

#### `MemoryOrchestrator`

In `run_operations_for_ctx` when we are waiting for new input sets, we'll now use the modification we did to `ctx.add`. The loop will need to be modified to be `for unvalidated_input_set, new_input_set in new_input_sets:`

You'll want to add another function similar to `dispatch` (and maybe `run_dispatch`) to grab the result of running the operation. Remember that we can only use single input / output operations here. So figure out what the name of the input should be and make it that for the `inputs` dict, and then do the same for the outputs, figure out the name and then extract that and use it as the value. You won't want to use the `run_dispatch` function because that creates inputs which assume they aren't valid if their is a validation parameter. Maybe just add an optional parameter to `run_dispatch` to make it so that when it creates the `Input` instances it sets their `validated` properties to `True`.

https://github.com/intel/dffml/blob/ad18dcc35c2b709d811cea6bd897e7868fec664d/dffml/df/memory.py#L1361-L1398
