### ISSUE TITLE
model: tensorflow: Refactor

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#383]
It's a mess!

**Comment by sk-ip** [comment]
@pdxjohnny , I would like to work on this issue, please provide some more details on what is needed to be done.

**Comment by pdxjohnny** [comment]
> @pdxjohnny , I would like to work on this issue, please provide some more details on what is needed to be done.

This was something @0dust brought up in a weekly sync. I think he was just thinking that the code was a bit of a mess and that it could use someone going over it and seeing where there could be more re-use of code and make things more neat.

**Comment by sk-ip** [comment]
@pdxjohnny , @0dust i went through the code and found
1.) the `DNNRegressionModelConfig` and `DNNClassifierModelConfig` dataclasses have some attributes which are common, which can be moved to a `BaseConfig` class.
2.) Some of the methods in `DNNRegressionModelContext` and `DNNClassifierModelContext` are common with a little difference which can be moved to `TensorflowModelContext`. which improves the code reusability.

I will open a pr to work on it.

**Comment by pdxjohnny** [comment]
@sk-ip Awesome! Thanks!
