### ISSUE TITLE
df: memory: Dispatch operations without inputs as soon as DataFlow begins

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#392]
We may have operations which need to be kicked off as soon as a dataflow starts, a good example would be something which is waiting for a message in a gitter channel, and the output it the message. This operation likely has no need for an input, it just returns the first message it sees. We'd want it to start waiting as soon as the dataflow started.

**Comment by us** [comment]
what types of operations need ?

**Comment by pdxjohnny** [comment]
@us Check out https://intel.github.io/dffml/master/tutorials/operations.html, an "operation" is a  DFFML term for anything that does work within a DataFlow. The purpose of this issues is to modify `dffml/df/memory.py` to make it so that if an operation takes no inputs, then it gets started when the dataflow starts.

This is where the orchestrator dispatches operations for running (they run whenever the event loop is free)

https://github.com/intel/dffml/blob/ad18dcc35c2b709d811cea6bd897e7868fec664d/dffml/df/memory.py#L1366-L1393

To fix this issue, it probably makes sense to add code around here

https://github.com/intel/dffml/blob/ad18dcc35c2b709d811cea6bd897e7868fec664d/dffml/df/memory.py#L1313-L1323

which does similar dispatching, but only for operations which have no inputs.

A test will also be necessary. `tests/test_df.py` for the Orchestrator might be a good place to copy from.
