### ISSUE TITLE
df: memory: async iterator operations

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#394]
Functions which are async iterators (`async def` with `yield`) should be supported by `@op`, as well as `dffml/df/memory.py` needs to be able to run one of these kinds of operations. Everytime the operation `yield`s, whatever it `yield`'d should be added to the input network context.

I think we'll likely want to combine `run` and `run_dispatch` so that we only have the `run` function, it's looking redundant (at first glance) *whoever submits a PR please figure this out and consolidate if appropriate*

https://github.com/intel/dffml/blob/7dfec5050c0e2f205fdd58524a420b861dc7fd9e/dffml/df/memory.py#L861-L976

**Comment by aghinsa** [comment]
@pdxjohnny to clarify,this is not [this to do](https://github.com/intel/dffml/blob/ad18dcc35c2b709d811cea6bd897e7868fec664d/dffml/df/memory.py#L1236).Also can you please provide a small example.

**Comment by pdxjohnny** [comment]
https://github.com/intel/dffml/blob/6da204fe5611d9a73bc71c77b9558e9ee4516f9f/dffml/noasync.py#L14-L31

**Comment by pdxjohnny** [comment]
https://github.com/intel/dffml/blob/6da204fe5611d9a73bc71c77b9558e9ee4516f9f/dffml/df/memory.py#L951-L1011

**Comment by pdxjohnny** [comment]
Refactor `run_dispatch` into two functions. The top level on is essentially going to do this:

https://github.com/intel/dffml/blob/6da204fe5611d9a73bc71c77b9558e9ee4516f9f/dffml/util/cli/cmd.py#L147-L152

Everything after line 974 becomes the new function, which gets called to handle the outputs, let's make `run_dispatch` not return anything (because we're not using it right now anyway and that's just confusing).

**Comment by aghinsa** [comment]
`return [res async for res in self.run()] `
@pdxjohnny is it okay to do this,if the async gen doesn't end won't this block?Im not sure if the event loop takes care of it somehow.

In case the above stuff doesnt work,i'm planning to change run_dispatch to an async iter and add tasks with the method in the comment before this one,thoughts?
