### ISSUE TITLE
df: Support operation redefintion for run_dataflow

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#415]
I realized something about the concept of forwarding. For this pull request we probably want to continue with what we discussed yesterday (only forward to active contexts).

For the other pull request (and also this will be helpful for shouldi and the upcoming subflows there) what we're interested in is really the **redefinition of the inputs to run_dataflow** (and also maybe the outputs by extension, but I haven't figured that out yet). Which isn't really "forwarding" because we're trying to kick off a new subflow, not forward inputs to a running subflow.

To illustrate what I'm talking about here let's look at something Rahul and I have been working on in another branch. We're trying to find the dependency tree of a given python package. [full file](https://github.com/pdxjohnny/dffml/blob/1bc5a787c78e21b169afa673d7facdcad511ac36/examples/shouldi/tests/test_dep_tree.py)

```python
@config
class ShouldIDataFlowAsOperationConfig:
    dataflow: DataFlow

@op(
    inputs={"package": pypi_package_json.op.inputs["package"]},
    outputs={"package": pypi_package_json.op.inputs["package"]},
    expand=["package"],
    config_cls=ShouldIDataFlowAsOperationConfig,
)
async def shouldi_dataflow_as_operation(self, package: str):
    async with self.octx.parent(self.config.dataflow) as octx:
        async for ctx, result in octx.run(
            {
                package: [
                    Input(
                        value=package,
                        definition=self.parent.op.inputs["package"],
                    )
                ]
            }
        ):
            packages = result[self.parent.op.inputs["package"].name]
            # Remove input package from list
            packages = list(filter(lambda pkg: pkg != package, packages))
            # TODO Deduplicate
            return {"package": packages}

dataflow = DataFlow.auto(shouldi_dataflow_as_operation, GetMulti)
dataflow.seed.append(
    Input(
        value=[pypi_package_json.op.inputs["package"].name],
        definition=GetMulti.op.inputs["spec"],
    )
)
dataflow.configs[
    "shouldi_dataflow_as_operation"
] = ShouldIDataFlowAsOperationConfig(dataflow=SUBFLOW)
dataflow.flow["shouldi_dataflow_as_operation"].inputs["package"].append(
    "seed"
)
dataflow.update_by_origin()
return dataflow
```

What I ended up doing here was writing a custom `run_dataflow` operation. This way, it could takes a package as an input, runs the dataflow for that package, returns the output (which is a package) and runs the same dataflow again. The result is a nice long list of dependencies where all of those `Input` objects have their `parent` set to whatever package requires them.

The point is that it's basically the same as `run_dataflow`, the difference is the inputs and the outputs (which probably seems like a big difference, but from a usability standpoint I think this will be good. Given what we talked about in the [February 25th Weekly Sync @ 1:04](https://youtu.be/Ih9vkE9synY?t=3893) with regards to `@op` / `OperationImplementation` / `OperationImplementationContext`, we could change `run_dataflow` into a `OperationImplementationContext` (see `dffml/operation/output.py` for examples).

The new `run_dataflow` (`RunDataFlow` if it's a `Context` because it's a class) would look at it's `self.parent.op` and see what the names of it's inputs are. To start small, we should just support the one input -> one output case, similar to the above example.

We'll need to change the operation instantiation code within `MemoryOperationImplementationNetworkContext.instantiate` to make sure that the `operation` passed in is assigned to `opimp.op`. We probably also need to be careful here and test what happens if two `run_dataflow` operation implementations get loaded (my guess is we might need the help of `copy.deepcopy` or `type` to avoid overwriting the shared class property)

```python
    async def instantiate(
        self,
        operation: Operation,
        config: BaseConfig,
        *,
        opimp: OperationImplementation = None,
    ) -> bool:
        """
        Instantiate class registered with ____ entrypoint using pkg_resources.
        Return true if instantiation was successful.
        """
        if opimp is None:
            if await self.instantiable(operation):
                opimp = OperationImplementation.load(operation.name)
                opimp = type(opimp.__qualname__, (opimp,), {"op": operation})
            else:
                raise OperationImplementationNotInstantiable(operation.name)
        self.operations[
            operation.instance_name
        ] = await self._stack.enter_async_context(opimp(config))
```

**Comment by aghinsa** [comment]
@pdxjohnny  Nice!! I ran into a similar issue when i tried `dataflow_connect`,couldn't figure out how to connect more than two,because both of them will have `flow_inputs` as their input definition.So are we chucking current implementation of #368, or having both?

**Comment by pdxjohnny** [comment]
@aghinsa If you revert to the previous commit where you added inputs to all the active contexts, and removed the parts where any Inputs or InputSets might be kept in memory, we could merge #368. If you wanted to you could add the method we talked about to `OperationImplemenationContext` to simplify creation of a subflow, or you could just post that as an issue and you or someone else could get to it later.

**Comment by aghinsa** [comment]
@pdxjohnny I'll try to add the `context` part,i still have to figure out a way to test this.I'll try to push this through the weekend.
