### ISSUE TITLE
 docs: model: tensorflow hub: Include examples of how to use from Python API

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#435]
The model plugins page has command line examples but needs examples from Python as well.

Copy the format of the `examples/quickstart_filenames.py` file and add a `.. code-block:: python` section for each model, keeping the Python example consistent with the command line example for each model. Let's add the python example after the CLI example for each.

For the tensorflow hub model, the docstring of the `Model` needs to be updated.

**Edit:**

Here's a good example from when tensorflow was updated: https://github.com/intel/dffml/commit/e7aaeb1e1e2f1b2ce74d1fe6ecc6422bf6df178c

**Comment by TakshKamlesh** [comment]
Does this mean we should add docstrings in every class of the tfhub_models file? Or completely a new file in examples folder?

**Comment by pdxjohnny** [comment]
Wait on working minimal python example in issue https://github.com/intel/dffml/issues/537

**Comment by mHash1m** [comment]
I'd like to work on this issue.

**Comment by pdxjohnny** [comment]
@mHash1m Awesome! We have a start, but we need to convert it into the format that can be tested. So making the `model/tensorflow_hub/examples/` directory (similarly to the `model/tensorflow/examples/tfdnnr/` example shown in https://github.com/intel/dffml/commit/e7aaeb1e1e2f1b2ce74d1fe6ecc6422bf6df178c).

**Comment by pdxjohnny** [comment]
You could also do https://github.com/intel/dffml/issues/619 first and then not do the Python example with `literalinclude`, but with the normal `>>> ` instead.

**Comment by mHash1m** [comment]
@pdxjohnny sure thing. I'll start with 619.
