### ISSUE TITLE
docs: Do not include generated files in git history

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#475]
Let's stop tracking the generated files in the docs folder. It's creating issues.

**Comment by sk-ip** [comment]
I think the files which are to be ignored needed to be added in `.gitignore`. what are your views @pdxjohnny , i can make a pr if this solves the issue

**Comment by pdxjohnny** [comment]
@sk-ip sorry I thought i'd replied to this. Yes, you'll want to add them to the `.gitignore`, you'll also want to do a `git rm docs/plugins/dffml_*.rst` (I think)
