### ISSUE TITLE
docs: source: Add --prefix=~/.local to New Source Tutorial

### ISSUE THREAD

**Issue by Lactem** [intel/dffml#479]
The [setup instructions](https://intel.github.io/dffml/contributing/dev_env.html) suggest installing dffml to the ~/.local directory when getting setup to do development/contributions. Since people making new sources will be doing development/contributions, I think we should make a note of the `--prefix=~/.local` flag in the [new source tutorial](https://intel.github.io/dffml/tutorials/source.html#install-your-package).

People will probably want to install their new source in the normal production way that's currently listed, but it would be helpful to add a reminder for people first developing a source and testing it in development mode.

**Comment by pdxjohnny** [comment]
Good catch!
