### ISSUE TITLE
model: directory: Not calling directory.resolve() for pathlib directories

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#487]
When the model directories we're switched over to pathlib.Path objects, they ended up treating `~` as a literal rather than the home directory (because of a lack of a .resolve() call (or maybe expanduser()).

We need to set the directory property to it's resolved self.

```python
self.config = self.config._replace(directory=self.config.directory.resolve())
```

**Comment by abdallah197** [comment]
@pdxjohnny I would like to work on this, would it be suitable for a beginner?

**Comment by pdxjohnny** [comment]
> @pdxjohnny I would like to work on this, would it be suitable for a beginner?

Yes, probably, if you run any of the model commands in the documentation you'll see that it creates a `~` directory wherever you ran them from. I think the issue is that we need to add the above code in the `__init__` method of `dffml.model.model.Model`
