### ISSUE TITLE
model: scratch: Remove slr

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#499]
Remove the `model/scratch/dffml_model_scratch/slr.py` file and remove it's reference in `model/scratch/setup.py`.

This and #500 could / should be done at the same time or right after each other.

**Comment by sbs2001** [comment]
I am working on this

**Comment by mHash1m** [comment]
Hi @sbs2001, 
I'm working on #500 as it was assigned to me by @pdxjohnny . It's my understanding that you just have to remove the file and its reference in setup.py for fixing this issue. #500 suggests moving misc.py to dffml/model/slr.py, it's not the same file.

**Comment by sbs2001** [comment]
Alright @mHash1m , this issue is all yours
