### ISSUE TITLE
source: csv: Add update funcationality

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#5]
Remove the `_close` method from `CSVSource`, as `FileSource` would normally use this to open the file and call `dump_fd` on it.

https://github.com/intel/dffml/blob/d184e8e5b8adcf23a57dea745b0596cde59a9325/dffml/source/csvfile.py#L49-L50

Implement `dump_fd`, this will probably include adding new headers to the file.

Something like `prediction` for the `prediction.classification` and `confidence` for `prediction.confidence` might be appropriate.

https://github.com/intel/dffml/blob/d184e8e5b8adcf23a57dea745b0596cde59a9325/dffml/source/csvfile.py#L52-L54

**Comment by sudharsana-kjl** [comment]
Hi! I'd like to work on this issue

**Comment by pdxjohnny** [comment]
Awesome! That would be great, thank you! Just submit your PR whenever you're ready.

**Comment by sudharsana-kjl** [comment]
#17 Please check this PR
