### ISSUE TITLE
model: Use skel model to have slr be a part of main dffml package

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#500]
When the skel model was recently re-worked (`dffml/skel/model/REPLACE_IMPORT_PACKAGE_NAME/misc.py`) we removed the need for it to use any third party libraries. Which means we can now move it into the main package.

We should copy `dffml/skel/model/REPLACE_IMPORT_PACKAGE_NAME/misc.py` into `dffml/model/slr.py`, and add the entrypoint in the top level `setup.py`.

This and #499 could / should be done at the same time or right after each other.

**Comment by mHash1m** [comment]
I'm working on this. 
@pdxjohnny do we want our entry point to be for "misc" or slr? I suppose everything(including the entrypoint and the classes) should be changed to slr to clear out the ambiguity with "misc" wouldn't you say?

**Comment by TakshKamlesh** [comment]
I have remove the slr file and its reference in setup.py . Though system tests have started failing (returning module not found error) because it is referenced somewhere else as well
