### ISSUE TITLE
operations: io: Fixup example

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#539]
https://github.com/intel/dffml/blob/c0946b2d212239cfe4e470e63ab3da22c9cd97c4/dffml/operation/io.py#L116

copy the code here into a Python file and format it with black, then copy it back.

We also want to change

```python
    ...         definition=dataflow.definitions["DataToPrint"],
    ...         parents=None,)]
```

to

```python
    ...         definition=print_output.inputs["data"],
    ...     )
    ... ]
```

**Comment by Yash-Varshney** [comment]
@pdxjohnny, the problem in this issue also seems to be- 
on line 17, we define an operation by name of `AcceptUserInput` and again on line 37, we define a class by the same name of `AcceptUserInput`.
