### ISSUE TITLE
sources: file: Should take a pathlib.Path as filename

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#561]
Right now if we have a filesource and we pass it a `pathlib.Path` as the filename, it will throw errors.

If you remove the `str` call here the failing test(s) will show you all the things that are wrong.

https://github.com/intel/dffml/blob/41d18ffea176dbec49224eed73910dfca933868f/service/http/tests/test_cli.py#L286-L290

The best way to handle this is probably to do like the models do right now with their directory config parameter. Treat the filename as if it's always a `pathlib.Path`. If the call to instantiate the `FileSource` (or subclass of `FileSource`) passes in a `str`, convert it to a `pathlib.Path` object.

Fix all the code that assumes `config.filename` is going to be a string. Remove calls to `os.path.` where appropriate and replace with `pathlib` alternatives.

**Comment by sudharsana-kjl** [comment]
Hi @pdxjohnny!  I'd like to work on this issue

**Comment by pdxjohnny** [comment]
That would be great! Thanks @sudharsana-kjl :)
