### ISSUE TITLE
docs: plugins: Edit on GitHub button not working for plugins

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#562]
This probably going to involve some patching of the rtd theme, probably a heavy lift.

**Comment by 0dust** [comment]
@pdxjohnny I think this is because we don't have GitHub files for plugins anymore as we stopped tracking generated plugin docs. If this is indeed the case then probably we should just hide the `Edit on Github` button for plugin docs.

**Comment by pdxjohnny** [comment]
@0dust that's probably a good plan
