### ISSUE TITLE
util: net: Add some progress logging on downloads

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#563]
## Pain Point

Can't tell how long downloads are taking / when they will be complete.

## Proposed Solution

Use logging library to log progress every so often.

This can probably be done by adding a wrapper around [urllib.request.urlretrieve()](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve) similarly to how `sync_urlopen` is a wrapper around `urlopen()` which checks the protocol allowlist within `dffml/util/net.py`.

Then add a `from .log import LOGGER` to the top of `dffml/util/net.py` and use it in `cached_download` via some helper function or maybe `functools.partial` for the `reporthook` parameter of `urlretrieve`.

From the docs (with regards to what the function assigned to `reporthook` should expect as it's arguments:

> The third argument, if present, is a callable that will be called once on establishment of the network connection and once after each block read thereafter. The callable will be passed three arguments; a count of blocks transferred so far, a block size in bytes, and the total size of the file

**Comment by programmer290399** [comment]
I would love to work on this issue , anything you'd like to add @pdxjohnny ? , since it has been a long time you opened this issue.
