### ISSUE TITLE
docs: operation: Incorrect formatting for arguments

### ISSUE THREAD

**Issue by 0dust** [intel/dffml#593]
There should be a space between the parameter name and their type. This is the problem with all the [operations ](https://intel.github.io/dffml/master/plugins/dffml_operation.html). For example:
https://intel.github.io/dffml/master/plugins/dffml_operation.html#parameters

**Comment by pdxjohnny** [comment]
To fix this we probably need to switch the underlining around in the operation docstrings and the `scripts/docs/templates/` for all those `.rst` files.

**Comment by pdxjohnny** [comment]
Fixed in d1d2c3169f39a4e317c37339a84db3374d8ee9bf
