### ISSUE TITLE
docs: usage: Ice Cream sales demo

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#599]
The demo would be the ice cream sales demo, we've got the YYYY-MM-DD, number of ice cream cones sold, and the city. We'd have this data for a few cities, we then write an operation to grab the temp for the city on that day. We use the dataflow source, since that's more of what it is, to run the operation and get the temperature data, then run the temperature + day + number sold through the model. Then to show prediction we ask for a prediction of a different city on a different day and it'll give us the prediction.

**Comment by Naeemkh** [comment]
In this demo, is all data synthetic? What kind of prediction model do you have in mind?

**Comment by pdxjohnny** [comment]
Ya the plan is to generate some random data. We'll generate the data systematically though. We'll want to pick a few cities where we can estimate the temperature and put in matching numbers.

So for example, its usually pretty cold in Portland, but it gets hot during the summer, data might look like this:

```csv
"city","month","sales"
"Portland, OR, USA","04","5000"
"Portland, OR, USA","05","10000"
"Portland, OR, USA","06","30000"
"Portland, OR, USA","07","40000"
"Portland, OR, USA","08","40000"
"Portland, OR, USA","09","30000"
```

Then we'd do more cities, making up appropriate data by looking at the weather in those cities.

```csv
"Los Angles, CA, USA","04","50000"
"Los Angles, CA, USA","05","100000"
"Los Angles, CA, USA","06","300000"
"Los Angles, CA, USA","07","400000"
"Los Angles, CA, USA","08","400000"
"Los Angles, CA, USA","09","300000"
```

To do this we first need monthly temperature data for a select set of cities. We probably want to figure out how to download data en-mas from https://www.ncdc.noaa.gov/cdo-web/

We'll also need to get a database that tells us city population size so we can fudge appropriate numbers there.

We'll want to make operations which know how to get population given city name, and another one that can get monthly data given city name.

We'll want to take that temperature data and city names and generate a ton of examples, making sure that they make sense. This means that cities of the same size with the same population and the same temperature end up with around the same sales for that month.

This can be done by providing a list of city names and running them through the two operations we just made, we'll want another operation which applies some kind of basic linear function to determine the number of ice cream sales for that month (we should add some noise to this). This will give us our example dataset, the process for doing this is very similar to the "Automating Classification" usage example, we're essentially using the linear function to generate the value we're going to try to predict though since this is just a demo.

We then have an alternate dataflow that doesn't include the linear function, so just grabs the temp for that month, and the population. We use this dataflow in conjunction with the dataflow source to transform the records in the example above into what we were using as the input data to our fake data function before. Only this time, we don't have that function in the dataflow, we just take those datapoints the operations get us for that city + month combo and feed them through a model (probably tfdnnr). We tell the model that we're trying to get it to predict the number of sales.

After we have the trained model we show how this can be used for prediction by providing a few city names that we didn't have in the training data.
