### ISSUE TITLE
service:http:New ouput presentation modes in HttpChannelConfig

### ISSUE THREAD

**Issue by aghinsa** [intel/dffml#608]
In [pr 570](https://github.com/intel/dffml/pull/570) new input_modes are added to HttpChannelConfig,
we want to add similar options for output modes (presentation). We also need a test for the added input modes

https://github.com/intel/dffml/blob/98c07eaeb9d5c7762a8efa1a0cf2ec242fe536c9/service/http/dffml_service_http/routes.py#L189-L243

**Comment by pdxjohnny** [comment]
Let's also make it so that we rename presentation to `output_mode`, to be consistent with `input_mode`
