### ISSUE TITLE
cli: list: Change to json dump

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#610]
Listing records shows the following (dffml list records ...):

```
$ cat > data.csv << EOF                                           
key,third_party,maintained
dffml,True,True
python,False,True
EOF
$ dffml list records -sources data=csv -source-filename data.csv
dffml
third_party                   True
maintained                    True
Predictions
Undetermined
python
third_party                   False
maintained                    True
Predictions
Undetermined
```

We should make it look better somehow, or just yield each one and not print so it gets dumped as json

**Comment by sk-ip** [comment]
to solve this issue i have  https://github.com/intel/dffml/blob/8b6db3d3f64650ed883244b05cccfe1459a0b528/dffml/cli/list.py#L18 

i changed `print(record)` to `print(record.export()`

and here's the output:
``` console
$ dffml list records -sources data=csv -source-filename data.csv
{'key': 'dffml', 'features': {'third_party': True, 'maintained': True}, 'extra': {}}
{'key': 'python', 'features': {'third_party': False, 'maintained': True}, 'extra': {}}
```
does it look good, i can make a pr if needed...

**Comment by pdxjohnny** [comment]
Let's replace the `print(record)` with a `yield record`
