### ISSUE TITLE
model: tensorflow: 2.2.0 Support

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#621]
Yesterday (May 7th 2020) TensorFlow 2.2.0 was released. It looks like it broke
something. Probably related to the docstring parsing we're doing to generated
configs.

Going to temporarily set the install range to `>=2.0.0,<2.2.0`

Ping: @0dust

**Comment by pdxjohnny** [comment]
When we fix this we should re-enable the Python 3.8 in `.github/workflows/testing.yaml` by removing the tensorflow dependent packages from the `if` statement that is exiting 0 if we're on Python 3.8.

**Comment by 0dust** [comment]
@pdxjohnny I am working on it.
