### ISSUE TITLE
model: daal4py: New Model daal4py

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#632]
Let's make a model to wrap something in https://github.com/IntelPython/daal4py

The https://intelpython.github.io/daal4py/streaming.html#streaming doc makes it
looks like the `.compute` call will go nicely in the body of the
`async for record in sources.with_features(` loop that's usually in the `train`
method of every model.

Steps to complete this issue are as follows. Please open a pull request and
prefix the title with `WIP: ` so that we know it's a work in progress. Ask for
help at any point, and once it's ready for final review (you think it's good
enough to merge, remove the `WIP: ` prefix from the title).

1. Go through the new model tutorial
2. Figure out how to download and install daal4py (probably will need to setup a
   Python 3.7 conda environment)
  - Now might be a good time to make some notes for when you do (5)
3. Figure out how to do linear regression with daal4py
4. Modify the simple model provided when you create the model with the `dffml
   service dev create model` command so that it uses daal4py.
5. Modify `.github/workflows/testing.yaml` so that it know's how to install
   daal4py.

**Comment by mHash1m** [comment]
I'll dive in and get working on it soon.
