### ISSUE TITLE
df: types: Support entrypoint style loading of operations

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#633]
Right now we have to create a whole Python package in order to have a DataFlow
load an operation (and register it with the entrypoints system).

It would be good if we could write dataflow files and use the `dataflow create`
command with operations in Python files that are not registered as entrypoints.

For example, if we had `func` function in `path/to/file.py` and we wanted to
make a DataFlow out it and the `GetSingle` operation, completeing this issue
would allow us to run `dataflow create` like so:

```console
$ dffml dataflow create -config yaml path.to.file:func GetSingle | tee df.yaml
definitions:
  get_single_output:
    name: get_single_output
    primitive: map
  get_single_spec:
    name: get_single_spec
    primitive: array
  model_predictions:
    name: model_predictions
    primitive: Dict[str, Any]
  record_features:
    name: record_features
    primitive: Dict[str, Any]
flow:
  path.to.file:func:
    inputs:
      features:
      - seed
  get_single:
    inputs:
      spec:
      - seed
linked: true
operations:
  path.to.file:func:
    inputs:
      features: record_features
    name: path.to.file:func
    outputs:
      prediction: model_predictions
    stage: processing
  get_single:
    inputs:
      spec: get_single_spec
    name: get_single
    outputs:
      output: get_single_output
    stage: output
```

> Here I just swapped `dffml.model.predict` for `path.to.file:func` for the sake
> of the example.

We'll need to modify the `dataflow create` command as well as `Operation.load`
and `OperationImplementation.load` so that they use `dffml.util.entrypoint.load`
if they see a `:` in the name (`loading`).

After this, let's convert the ffmpeg usage demo so that we don't need to make a
package, we just need to have a `ffmpeg.py` file.

**Comment by pdxjohnny** [comment]
Looks like we might have some code to do this in `dffml/df/types.py` in https://github.com/intel/dffml/pull/274

**Comment by aghinsa** [comment]
@pdxjohnny  
`dffml dataflow create -config yaml path.to.file:func GetSingle | tee df.yaml`
It'd be also nice to have someway to specify what spec the output operation should get,
does `GetSingle:definition` work?

**Comment by pdxjohnny** [comment]
@aghinsa That would be great. I don't follow though. Could you show the full syntax?

**Comment by pdxjohnny** [comment]
For adding to `seed` let's copy how `-inputs` works, but change it to `-seed`

https://github.com/intel/dffml/blob/cab9c3efddec0a96fbc24b32bb06fc8859064b18/dffml/cli/dataflow.py#L141-L148
