### ISSUE TITLE
util: packaging: is_develop should check if package name with _ or - has .egg-link

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#648]
https://github.com/intel/dffml/blob/23064bcb5de738b98007ffc3225516c24eb27d84/dffml/util/packaging.py#L15-L18

**Comment by aadarshsingh191198** [comment]
@pdxjohnny I want to work on this but am not sure as to what exactly is wanted. Could you please guide me?

**Comment by pdxjohnny** [comment]
@aadarshsingh191198 Python will sometimes create `.egg-link` files for packages that contain `-` in the name where the `.egg-link` file has the package name but with `-` replaced with `_`.

We just need to put the above block into a loop were the first iteration of the loop just does the check as it does it now, and the second iteration checks for the presence of the `.egg-link` file but with the package name where `-` has been replaced with `_`. This will ensure that if Python installed it with `_` in the name, we still detect it successfully.

**Comment by aadarshsingh191198** [comment]
Thanks ... Now I understood the problem. Will start working on it asap!!

**Comment by aitikgupta** [comment]
I see the check still hasn't been added yet. Is it okay if I take this up?
/cc @aadarshsingh191198 @pdxjohnny

**Comment by aadarshsingh191198** [comment]
Ya sure you can. I got busy in some work so will not be able to take this right now.
