### ISSUE TITLE
model: scikit: Data type of feature used for predict not respected

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#651]
Predicted values are comming out as floats from regression models. We should
typecast to the feature's dtype.

**Comment by pdxjohnny** [comment]
Specifically if we have a float we should round to an int if the dtype is int

**Comment by pdxjohnny** [comment]
Check out `model/scikit/dffml_model_scikit/scikit_base.py` within the predict method. We should cast the type to `self.config.predict.dtype` before calling [Record.predicted](https://intel.github.io/dffml/master/api/record.html#dffml.record.Record.predicted)

**Comment by aadarshsingh191198** [comment]
Hi @pdxjohnny, can you please help me with the tests which are failing? `(model/scikit, 3.7)`, `(model/scikit, 3.8)` and `(model/xgboost, 3.8)`. The error shows 

> AssertionError: '0' not found in [-1, 0, 1, 2, 3, 4, 5, 6, 7]

Now, why would someone check for a string in an array of `int`s. Also, why is the error only in these 3 models?

**Comment by pdxjohnny** [comment]
It should not be checking for a string. That's is the issue here. Don't worry about `model/xgboost` that is an intermittent failure.

It is currently checking for a string because of the change you made, with means the change was either not entirely correct, or the tests also need updating somehow.

**Comment by aadarshsingh191198** [comment]
Okay, I will look into it once again keeping in mind the tests for `model/scikit` ... Thanks for the guidance.

**Comment by B-Anupam** [comment]
Hey!
I am Interested in Machine Learning projects and looking openly for a contribution. 
Please let me know how can I contribute to this issue?

**Comment by pdxjohnny** [comment]
@B-Anupam This issue was just fixed (thank you @sidhu1012!). Issue #867 seems like a good target for a first contribution. Please read the contributing documentation first: https://intel.github.io/dffml/master/contributing/index.html
