### ISSUE TITLE
noasync: Expose high level save and load

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#659]
We need the `noasync` API to also include the `save`, `load`, and `run`
functions within `dffml.high_level`.

**Comment by sk-ip** [comment]
i would like to work on this issue

**Comment by pdxjohnny** [comment]
Sweet! Thank you! When you get to the docstring portion of things be aware that the docstring for `run` will probably need to be re-written because of `send_to_server` won't still work with the simple find and replace that is being done on the other docstrings

**Comment by pdxjohnny** [comment]
You'll probably just need to replace it with some regular socket calls
