### ISSUE TITLE
shouldi: Use op auto definition creation

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#664]
[op](https://intel.github.io/dffml/master/api/df/base.html#dffml.df.base.op) got the ability to auto create definitions by inspecting the return types of functions it wraps. We should change all the user facing examples in documentation so that they use this functionality.

**Comment by sk-ip** [comment]
@pdxjohnny , i am planning to do this, with multiple pull requests. so that they can be individually merged. and we can keep track of which documentations have been updated.
