### ISSUE TITLE
model: tensorflow: Create DNNEstimator based model

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#75]
Make DNN predict a non-classification problem, for example maybe a dataset like this

```
owls,hawks,mice
3,5,20
2,6,32
5,4,29
```

And have the model predict the number of mice given the number of owls and hawks.

This will involve creating a new model, based on DNNEstimator rather than DNNClassifier

**Comment by aghinsa** [comment]
@pdxjohnny i have made a [pull request](https://github.com/intel/dffml/pull/226)
