### ISSUE TITLE
skel: Replace usage of pkg_resources with importlib.resources

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#783]
Just came across this: https://docs.python.org/3/library/importlib.html#importlib.resources.path

We should get rid of some usages of `pkg_resources` within our codebase. This would make it so we could be `zip_safe`!

**Comment by Nishikoh** [comment]
Hi, I'd like to tackle that.

**Comment by pdxjohnny** [comment]
@Nishikoh Awesome! Just let me know, or anyone on Gitter if you need more info. This should be a case of finding all the `pkg_resources.resource_filename` and changing them

```console
$ git grep pkg_resources | grep resource_
dffml/util/skel.py:    pkg_resources.resource_filename("dffml", "skel")
service/http/dffml_service_http/routes.py:    pkg_resources.resource_filename("dffml_service_http", "api.js")
```
