### ISSUE TITLE
df: types: Autoconvert Definitions with spec into their spec

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#86]
Conversion should happen upon instantiation of an `Input`, if the `value` is a `dict` and the definition has a `spec`, convert the `dict` into and instance of class provided by the `spec` and use that as the `value`.

https://github.com/intel/dffml/blob/01a3deb4bfa01bd1ce8ff690358b46d8b1e037bc/dffml/df/types.py#L253-L278

For testing that this works, modify the git feature operations which use `git_repository` and `git_repository_checked_out`.

https://github.com/intel/dffml/blob/01a3deb4bfa01bd1ce8ff690358b46d8b1e037bc/feature/git/dffml_feature_git/feature/operations.py#L273-L348

`repo["directory"]` will become `repo.directory`, etc. There are more operations towards the top of the file that will need modification. Hold off on changing `clone_git_repo` until we have a working pull request.

Definitions and specs for reference:

https://github.com/intel/dffml/blob/01a3deb4bfa01bd1ce8ff690358b46d8b1e037bc/feature/git/dffml_feature_git/feature/definitions.py#L7-L35

**Comment by sudharsana-kjl** [comment]
@pdxjohnny I'd like to work on this issue.
