### ISSUE TITLE
dffml: plugins: Autosklearn should not be added for Windows OS

### ISSUE THREAD

**Issue by yashlamba** [intel/dffml#887]
Just went through this: https://automl.github.io/auto-sklearn/master/installation.html#windows-osx-compatibility

It's an easy fix, to check for the os and then add it to the plugins list.

**Comment by SGeetansh** [comment]
Is it okay if I give it a shot?

**Comment by pdxjohnny** [comment]
@SGeetansh Yes! The plugins list is in `dffml/plugins.py`, look for the if block around `daal4py` and how it isn't added to the list for Python 3.8. Do the same for autosklearn if `platform.system()` is "Windows". A `CHANGELOG.md` entry is not necessary for this PR.

**Comment by SGeetansh** [comment]
Should I check just for Windows or macOS too? Because I don't think it supports macOS for now.
https://automl.github.io/auto-sklearn/master/installation.html#mac-osx

**Comment by pdxjohnny** [comment]
Ah, yes. Please do.
