### ISSUE TITLE
plugins: Move install_requires into requirements.txt

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#890]
We need to go through all the `setup.py` and `setup_common.py` for each plugin and take anything in the `install_requires` and move it to a `requirements.txt` file within the same directory. Then we need to modify `setup_common.py` (or `setup.py` if there is no `setup_common.py`) similar to how was done in 4867b4c1d6b1a51ef89e3926d0561a5502ad2850

```python
REQUIREMENTS_TXT_PATH = Path(SELF_PATH, "requirements.txt")
if REQUIREMENTS_TXT_PATH.is_file():
    INSTALL_REQUIRES += list(
        map(lambda i: i.strip(), REQUIREMENTS_TXT_PATH.read_text().split("\n"))
    )
```

**Comment by pdxjohnny** [comment]
We're doing because various static analysis tools don't support reading dependencies from `setup.py`. They fail to detect them.

This is also preparation for pinning the version numbers of dependencies when we do the release. We're going to make so that in every released version all the dependencies for each plugin are pinned to a given version with `==` so that new versions which might break our compatibility are never installed for end users.

**Comment by pdxjohnny** [comment]
The next thing towards pinning is that we need to get the list of installed dependencies and their version for each plugin.

We should probably install `pipdeptree` in the CI, then after installing the plugin run `pipdeptree` to dump the list of installed deps with their versions to the CI output. We can then take the last good CI run before release and copy paste the version in the `requirements.txt` files.

**Comment by SGeetansh** [comment]
Is it okay if I work on this?

**Comment by yashlamba** [comment]
@SGeetansh, Go ahead and let me know if you need any help! Try following the first comment for one plugin and then move on to the others. A good starting point would be any of the [model](https://github.com/intel/dffml/tree/master/model) plugins :)

**Comment by SGeetansh** [comment]
@yashlamba @pdxjohnny 
How should I deal with this? Should I just move it to setup_common.py just like every other module?

https://github.com/intel/dffml/blob/6405f996d77df5ff749f9d5fa287fe7b08f528c5/model/autosklearn/setup.py#L12

**Comment by pdxjohnny** [comment]
@SGeetansh Anytime you see a case like this where there is both a `setup.py` and `setup_common.py` in the same directory. Add

```python
REQUIREMENTS_TXT_PATH = Path(SELF_PATH, "requirements.txt")
if REQUIREMENTS_TXT_PATH.is_file():
    common.KWARGS["install_requires"] += list(
        map(lambda i: i.strip(), REQUIREMENTS_TXT_PATH.read_text().split("\n"))
    )
```

to the `setup_common.py`

Remove anything that has been added to `install_requires` within `setup.py` or `setup_common.py` and put it in `requirements.txt`. **Do not** modify or remove the code related to `dffml` or `dffml-*-*` which will look like this:

```python
(
    ["dffml>=0.3.7"]
    if not any(
        list(
            map(
                os.path.isfile,
                list(
                    map(
                        lambda syspath: os.path.join(
                            syspath, "dffml.egg-link"
                        ),
                        sys.path,
                    )
                ),
            )
        )
    )
    else []
)
```

**Comment by pdxjohnny** [comment]
@SGeetansh any progress on this? Let us know if you get stuck

**Comment by SGeetansh** [comment]
@pdxjohnny Really sorry for the delay. Got super busy with a college project.

**Comment by pdxjohnny** [comment]
No worries! Thanks!
