### ISSUE TITLE
source: Labeled and Versioned datasets

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#9]
Assignee: @sudharsana-kjl

DFFML is hoping to participate in Google Summer of Code (GSoC) under the Python Software Foundation umbrella.  You can read all about what this means at http://python-gsoc.org/.  This issue, and any others tagged `gsoc` and `project` are not generally available bugs, but related to project ideas for GSoC.

# Project Idea: Labeled and Versioned Datasets.

**Project description:** 
DFFML's initial release includes sources which abstract the format in which the data is stored from the dataset generation and usage in models.

Add information allowing users to have different versions and datasets from the same source.

**Skills:** Python, git
**Difficulty level:** Intermediate

**Related Readings/Links:**

https://github.com/intel/dffml/blob/dd8007d0c9f8c58c35c94faf148e2b5d6ce4c101/dffml/source/source.py#L16-L45

https://github.com/intel/dffml/blob/dd8007d0c9f8c58c35c94faf148e2b5d6ce4c101/dffml/repo.py#L90-L116

**Potential mentors:** @pdxjohnny

**Getting Started:** `Source.__init__` probably needs another two arguments, `label` and `version`, which should probably have defaults (say, `default` and `v0`). Since the same backend (aka, a csv file or json file) would be used to store all the data, you'll have to change the existing sources we have to understand how to deal with this. For `CSVSource` that might mean adding another column to each repo, for `JSONSource` that might mean instead of one big array, the array of repos is stored like so:

```json
{
    "default": {
        "v0": [
            "... all the repos ..."
        ]
    }
}
```

**What we want to see in your application:** Describe how you intend to solve the problem, and give us some "stretch goals", maybe you'll implement a source using `sqlite` too or something. Don't forget to include some time for building appropriate tests.

**Comment by CYBruce** [comment]
Hi, @pdxjohnny . This is Chenyu Tian from China. I am an undergrad at Sun Yat-Sen University. I use Python frequently and have learned machine learning algorithms. I would like to contribute to this issue to the best of my ability. I would like to ask where should I start to make my first commit? Because I still feel a little confused about the 'getting started' part
And I guess there is a small mistake in the wiki that it should be a 'with' instead of 'will'.
<img width="734" alt="wiki" src="https://user-images.githubusercontent.com/34786389/54577872-6125c500-4a38-11e9-960e-80c14382aa2c.png">

**Comment by pdxjohnny** [comment]
Thanks for letting me know! I'll fix that! If you're more familiar with machine learning models it might be good if you implemented a DFFML `Model`. To do that you would follow the [new model tutorial](https://github.com/intel/dffml/blob/master/docs/tutorial/MODEL.md) then you replace the functions in that class with code which calls to some machine learning library.
