### ISSUE TITLE
cleanup: Remove --use-feature=2020-resolver everywhere

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#912]
The latest version of pip (which we require users to update to) uses the new resolver by default (yay!) so we can remove all the additions of the feature flag.

Anywhere you see it, remove it. With the docs it should be pretty straightforward. However, there may be some slightly more interesting code paths in `.py` files, there shouldn't be many though.

**Comment by Devansh252** [comment]
Can you assign me this issue?

**Comment by pdxjohnny** [comment]
I can't do it through GitHub due to the way the intel/ org is set up. But you can consider it yours :)

**Comment by Devansh252** [comment]
sure, Thanks !
