### ISSUE TITLE
plugins: Remove reading in requirements.txt and adding to INSTALL_REQUIRES in setup*.py

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#964]
We found out that we don't need to have both requirements.txt files and add
those requirements to `install_requires` of `setupools.setup()`.

We can remove the following code blocks.

```diff
diff --git a/model/pytorch/setup_common.py b/model/pytorch/setup_common.py
index 171173c8..01bc38b6 100644
--- a/model/pytorch/setup_common.py
+++ b/model/pytorch/setup_common.py
@@ -49,12 +49,6 @@ VERSION = ast.literal_eval(
 
 README = Path(SELF_PATH, "README.md").read_text()
 
-REQUIREMENTS_TXT_PATH = Path(SELF_PATH, "requirements.txt")
-if REQUIREMENTS_TXT_PATH.is_file():
-    INSTALL_REQUIRES += list(
-        map(lambda i: i.strip(), REQUIREMENTS_TXT_PATH.read_text().split("\n"))
-    )
-
 KWARGS = dict(
     name=NAME,
     version=VERSION,
```

**Comment by pdxjohnny** [comment]
https://www.python.org/dev/peps/pep-0440/
- Local version identifiers (the +) `torchvision===0.8.2+cu110`


https://www.python.org/dev/peps/pep-0508/
  - Environment Markers
    - python_version
    - platform_system

https://www.python.org/dev/peps/pep-0517/
- New style build system / packaging PEPs using `pyproject.toml` (and `setup.cfg`)
- Also https://www.python.org/dev/peps/pep-0518/ is interesting
- setup.cfg help
  - https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html

**Comment by pdxjohnny** [comment]
Just to recap

- We moved everything to requirements.txt so we could scan with Synk
- Synk found issues with TensorFlow < 2.4.0
  - We need to update or remove model/transformers because of this before the 0.4.0 release
- Before release we also need to make sure that we pin all the versions of all the dependencies to known versions that work together.
  - On different OSs (Linux, Windows, MacOS, etc.) different versions of dependencies or different packages may be required.
  - As such we need to be able to use Environment Markers
    - Some of these are supported within `setuptools.setup(install_requires=[...])`, some are not. `platform_system` is not. However, it is supported if you use requirements.txt. However, we can't figure out how to make it so that when pip installs one of our packages to have it look in both the `setup.py` `install_requires` AND `requirements.txt`.
    - Therefore, we're exploring moving to PEP-517/518 style packages where most everything is in the `setup.cfg` file, including what used to be in `requirements.txt`
      - This poses another issue where `.` is not allowed in entry point names if they are defined within a `setup.cfg` file, so we're going to have to re-name all the entry point names to replace underscores with periods.

**Comment by pdxjohnny** [comment]
@yashlamba  and I have done some work on this so far in the model_tensorflow_upgrade_to_2_4_0 branch

**Comment by yashlamba** [comment]
I researched a bit and have a few points that might be of use:
1.  [Here](https://support.snyk.io/hc/en-us/articles/360004699377-Snyk-for-Python) it says:
>In order to build the dependency tree Snyk analyzes the setup.py file, and detects packages listed in the install_requires key. There is no auto-discovery for this file, it must be specified manually: `snyk test --file=setup.py`
>You can convert setup.py to requirements.txt by installing the packages into a virtual environment then running pip freeze. 

Have we tried this?

2. Since requirements.txt just lists all the arguments to the `pip install` command, would it work with Snyk if we just put a "." in requirements and list all the dependencies in `setup.py`.

**Comment by pdxjohnny** [comment]
Well the Synk scan isn't really the priority anymore but that is good to know.

I think our main issue is that we need to get something that lets us do the pinning
