### ISSUE TITLE
df: base: op: Add keyword argument to toggle interpretation of None

### ISSUE THREAD

**Issue by pdxjohnny** [intel/dffml#978]
Add a boolean keyword argument to [`@op`](https://intel.github.io/dffml/master/api/df/base.html?highlight=op#dffml.df.base.op) to toggle interpretation of the wrapped function's return value.

`valid_return_none` might be a good choice. If `valid_return_none` is true. Then we should build the result dict

References:
- 51d5a979dcb3e54ab970c5fc84b56d62cd908bcf

**Comment by sidhu1012** [comment]
What exactly needs to be done here? As much as I understood a new argument is to be added to  here
https://github.com/intel/dffml/blob/fc54136096bf71baed5a59228b910654f6bcc7ea/dffml/df/base.py#L255

**Comment by pdxjohnny** [comment]
You understand correctly. Another keyword argument needs to be added to the `op` function.

**Comment by Saanidhyavats** [comment]
If no one is working on it then I am taking up this issue.
